import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ==================== Home Page ====================
    'home.tagline': 'System Online // V2.5',
    'home.title.line1': 'Let Time',
    'home.title.line2': 'Be Your Ally',
    'home.subtitle': 'The First PID-Controlled Structured Bond Protocol.',
    'home.subtitle.highlight': 'Algorithmic Stability // Yield Optimization',
    'home.cta': '[ Initialize Mint ]',
    'home.cta.locked': '[ SYSTEM LOCKED ]',
    'home.cta.minting': '[ MINTING... ]',
    
    // ==================== Navigation ====================
    'nav.protocol': 'PROTOCOL',
    'nav.nodes': 'NODES',
    'nav.yield': 'YIELD',
    'nav.team': 'TEAM',
    'nav.docs': 'DOCS',
    'nav.connect': 'Connect Wallet',
    'nav.faucet': 'FAUCET',
    
    // ==================== Common ====================
    'common.access_denied': 'ACCESS DENIED',
    'common.return_home': '[ RETURN HOME ]',
    'common.connect_wallet': 'Please connect your wallet',
    'common.approve': '[ APPROVE USDT ]',
    'common.approving': '[ APPROVING... ]',
    'common.approved': '✓ APPROVED',
    
    // ==================== Nodes Page ====================
    'nodes.console': 'NODE CONSOLE // IDENTITY LAYER',
    'nodes.title': 'GENESIS NODES',
    'nodes.description': 'Purchase and manage your Genesis Node NFTs. Each node grants permanent mining boosts and network privileges.',
    'nodes.privileges': 'NODE PRIVILEGES',
    'nodes.self_boost': 'Self Boost',
    'nodes.self_boost_desc': 'Permanent mining power increase for node holders',
    'nodes.team_aura': 'Team Aura',
    'nodes.team_aura_desc': 'Bonus granted to all your direct referrals',
    'nodes.max_supply': 'Max Supply',
    'nodes.max_supply_desc': 'Limited edition Genesis Nodes - first come, first served',
    
    // ==================== Identity Panel ====================
    'identity.title': 'IDENTITY & ACCESS',
    'identity.subtitle': 'Genesis Node Membership',
    'identity.current': 'Current Identity',
    'identity.visitor': 'VISITOR',
    'identity.genesis_node': 'GENESIS NODE',
    'identity.active': 'ACTIVE',
    'identity.privilege_boosts': 'PRIVILEGE BOOSTS',
    'identity.total_boost': 'Total Mining Boost',
    'identity.your_network': 'Your Network',
    'identity.direct_referrals': 'Direct Referrals',
    'identity.supply': 'Supply',
    'identity.node_price': 'Node Price',
    'identity.buy_node': '[ BUY GENESIS NODE ]',
    'identity.buying': '[ BUYING... ]',
    'identity.not_deployed': 'Contract Not Deployed',
    'identity.deploy_first': 'Deploy GenesisNode contract first',
    
    // ==================== Yield Page ====================
    'yield.terminal': 'YIELD TERMINAL // INVESTMENT LAYER',
    'yield.title': 'TREASURY BONDS',
    'yield.description': 'Deposit USDT to earn IVY tokens. Your investment is automatically distributed across liquidity, RWA, and reserve pools.',
    'yield.genesis_active': 'Genesis Node Active',
    'yield.boost_message': 'Your mining rewards are boosted',
    'yield.no_node': 'No Genesis Node',
    'yield.no_node_desc': 'Purchase a Genesis Node to unlock +10% mining boost and +2% team aura.',
    'yield.go_to_nodes': 'Go to Node Console',
    'yield.fund_distribution': 'FUND DISTRIBUTION',
    'yield.liquidity_pool': 'Liquidity Pool',
    'yield.liquidity_desc': 'DEX Trading Pairs',
    'yield.rwa_wallet': 'RWA Wallet',
    'yield.rwa_desc': 'Real World Assets',
    'yield.reserve_pool': 'Reserve Pool',
    'yield.reserve_desc': 'Protocol Insurance',
    'yield.referral_rewards': 'REFERRAL REWARDS',
    'yield.l1_direct': 'L1 Direct',
    'yield.l2_indirect': 'L2 Indirect',
    'yield.l3_infinite': 'L3+ Infinite',
    'yield.rewards_note': 'Rewards are minted from the Mining Pool, not deducted from user principal.',
    'yield.how_it_works': 'HOW IT WORKS',
    'yield.step1': 'Deposit',
    'yield.step1_desc': 'Deposit USDT to create your bond',
    'yield.step2': 'Split',
    'yield.step2_desc': 'Funds distributed 50/40/10',
    'yield.step3': 'Mine',
    'yield.step3_desc': 'Earn IVY tokens daily',
    'yield.step4': 'Claim',
    'yield.step4_desc': 'Claim rewards every 24h',
    
    // ==================== Treasury Panel ====================
    'treasury.title': 'TREASURY & YIELD',
    'treasury.subtitle': 'Investment & Mining Rewards',
    'treasury.my_principal': 'My Principal',
    'treasury.bond_power': 'Bond Power',
    'treasury.pool_share': 'Pool Share',
    'treasury.est_daily': 'Est. Daily',
    'treasury.total_claimed': 'Total Claimed',
    'treasury.referral_earnings': 'Referral Earnings',
    'treasury.fund_distribution': 'Fund Distribution (50/40/10)',
    'treasury.liquidity': 'Liquidity',
    'treasury.rwa': 'RWA',
    'treasury.reserve': 'Reserve',
    'treasury.deposit_usdt': 'Deposit USDT',
    'treasury.balance': 'Balance',
    'treasury.deposit_earn': '[ DEPOSIT & EARN ]',
    'treasury.depositing': '[ DEPOSITING... ]',
    'treasury.not_deployed': 'Contract Not Deployed',
    'treasury.deploy_first': 'Deploy IvyBond contract first',
    
    // ==================== Referral Center ====================
    'referral.title': 'REFERRAL UPLINK',
    'referral.description': 'Earn 10% rewards from direct invites and 5% from secondary invites.',
    'referral.your_link': 'Your Unique Link',
    'referral.connect_to_generate': 'Connect Wallet to Generate',
    'referral.copy': 'Copy',
    'referral.copied': 'Referral link copied to clipboard',
    'referral.stats': 'Referral Stats',
    'referral.direct': 'Direct Referrals',
    'referral.direct_refers': 'Direct Refers',
    'referral.ref_rewards': 'Ref Rewards',
    'referral.total_earned': 'Total Earned',
    
    // ==================== My Nodes ====================
    'myNodes.title': 'MY NODES',
    'myNodes.wallet_not_connected': 'WALLET NOT CONNECTED',
    'myNodes.connect_to_view': 'Connect your wallet to view your Genesis Nodes.',
    'myNodes.no_nodes': 'NO NODES DETECTED',
    'myNodes.no_nodes_desc': 'Initialize a Genesis Node to begin earning yield.',
    'myNodes.contract': 'Contract',
    'myNodes.refresh': 'Refresh',
    'myNodes.genesis_node': 'GENESIS NODE',
    'myNodes.active': 'ACTIVE',
    'myNodes.boost': 'BOOST',
    'myNodes.tier': 'TIER',
    
    // ==================== Faucet ====================
    'faucet.title': 'TESTNET FAUCET',
    'faucet.subtitle': 'Development & Testing Only',
    'faucet.warning': 'This faucet provides test tokens for development purposes only. These tokens have no real value.',
    'faucet.your_balance': 'Your MockUSDT Balance',
    'faucet.amount': 'Faucet Amount',
    'faucet.use_for': 'Use For',
    'faucet.use_for_desc': 'Buy Node + Deposit',
    'faucet.claim_button': 'CLAIM 20,000 mUSDT',
    'faucet.claiming': 'CLAIMING...',
    'faucet.success': 'Tokens claimed successfully!',
    'faucet.not_deployed': 'Contract Not Deployed',
    'faucet.deploy_first': 'Deploy MockUSDT contract first',
    
    // ==================== Dashboard ====================
    'dashboard.daily_mint': 'Daily Mint',
    'dashboard.nodes': 'Nodes',
    'dashboard.your_balance': 'Your Balance',
    'dashboard.pid_status': 'PID Status',
    'dashboard.genesis': 'Genesis',
    'dashboard.boost_active': 'Boost Active',
    'dashboard.ivy_per_day': 'IVY / Day',

    // ==================== Treasury Panel (New Features) ====================
    'treasury.bond_nft_title': 'Bond NFT Treasury',
    'treasury.bond_nft_subtitle': 'ERC721 Mining Bonds (Whitepaper V2.5)',
    'treasury.my_bonds': 'My Bond NFTs',
    'treasury.total_deposit': 'Total Deposit (总投入)',
    'treasury.mining_principal': 'Mining Principal (矿机本金 50%)',
    'treasury.rwa_assets': 'RWA Assets (国债 40%)',
    'treasury.reserve_fund': 'Reserve (储备金 10%)',
    'treasury.tranche_b': 'TRANCHE B',
    'treasury.only_this_portion': 'Only this portion generates IVY mining rewards',
    'treasury.effective_power': 'Effective Mining Power',
    'treasury.formula': 'Formula',
    'treasury.network_share': 'Network Power Share',
    'treasury.your_power': 'Your Power',
    'treasury.total_network': 'Total',
    'treasury.ivy_price_title': 'IVY Price & Power Rate',
    'treasury.testnet': 'TESTNET',
    'treasury.current_price': 'Current IVY Price',
    'treasury.usdt_per_ivy': 'USDT per IVY',
    'treasury.compound_rate': 'Compound Rate',
    'treasury.power_per_ivy': 'Power per IVY (+10% bonus)',
    'treasury.price_formula': '1 IVY = ${price} × 1.1 (compound bonus) = {rate} Power',
    'treasury.pending_vivy': 'Pending Yield (vIVY)',
    'treasury.mining_rewards': 'Mining rewards (can compound)',
    'treasury.total_claimed_ivy': 'Total Claimed',
    'treasury.locked_ivy_title': 'Locked IVY (30-Day Vesting)',
    'treasury.unlocks_in': 'Unlocks in {days} days',
    'treasury.ready_to_claim': 'Ready to claim!',
    'treasury.standard_unlock': 'Standard Unlock (100%)',
    'treasury.instant_penalty': 'Instant (50% Penalty)',
    'treasury.compound_title': 'Compound (复投)',
    'treasury.compound_bonus': '+10% BONUS',
    'treasury.compound_desc': 'Whitepaper: "复投部分的资金给予 10% 的算力加成"',
    'treasury.compound_button': 'Compound into Bond NFT',
    'treasury.mining_not_synced': 'Mining Power Not Synced',
    'treasury.click_to_start': 'Click below to start earning rewards',
    'treasury.sync_now': 'Sync Now',
    'treasury.syncing': 'Syncing...',
    'treasury.mint_new_bond': 'Mint New Bond NFT',
    'treasury.min_deposit': 'Minimum deposit: 10 USDT',
    'treasury.insufficient_balance': 'Insufficient balance. Use faucet.',
    'treasury.mint_button': 'Mint Bond NFT & Earn',
    'treasury.minting': 'Minting Bond NFT...',

    // ==================== Harvest Section ====================
    'harvest.title': 'Harvest vIVY',
    'harvest.lock_badge': '30-DAY LOCK',
    'harvest.description': 'Convert vIVY mining rewards to locked IVY tokens. After 30 days, choose Standard Unlock (100%) or Instant Cash Out (50% penalty).',
    'harvest.available': 'Available vIVY:',
    'harvest.button': 'Harvest {amount} vIVY → Locked IVY',
    'harvest.harvesting': 'Harvesting...',
    'harvest.success': 'Harvest successful! {amount} vIVY locked for 30 days 🎉',
    'harvest.no_vivy': 'No vIVY to harvest',
    'harvest.info_toast': 'Harvesting {amount} vIVY → Starting 30-day vesting...',

    // ==================== Compound Modal ====================
    'compound.modal_title': 'Compound vIVY into Bond NFT',
    'compound.select_bond': 'Select Bond NFT',
    'compound.select_placeholder': 'Select a bond...',
    'compound.bond_nft': 'Bond NFT',
    'compound.available_vivy': 'Available vIVY (Pending Rewards):',
    'compound.amount_label': 'Compound Amount (vIVY)',
    'compound.enter_amount': 'Enter amount...',
    'compound.max': 'MAX',
    'compound.exceeds_available': 'Amount exceeds available vIVY',
    'compound.process_title': 'Compound Process:',
    'compound.step1': '1. vIVY → Convert to IVY → Burn to 0xdead',
    'compound.step2': '2. Query IVY price (Testnet: 1 IVY = 1 USDT)',
    'compound.step3': '3. Calculate power with 10% bonus',
    'compound.bonus_calc': 'Bonus Power Calculation:',
    'compound.no_vivy': 'No vIVY available to compound',
    'compound.need_harvest': 'You need to harvest rewards first',
    'compound.cancel': 'Cancel',
    'compound.confirm': 'Compound vIVY',
    'compound.compounding': 'Compounding...',

    // ==================== Withdraw Modal ====================
    'withdraw.standard_title': 'Standard Unlock (30 Days)',
    'withdraw.instant_title': 'Instant Cash Out (50% Penalty)',
    'withdraw.locked_amount': 'Locked IVY Amount:',
    'withdraw.unlock_complete': '✅ Unlock Complete!',
    'withdraw.unlock_desc': 'You can now claim your full locked amount with no penalty.',
    'withdraw.you_receive': 'You will receive:',
    'withdraw.still_locked': '⏳ Still Locked',
    'withdraw.unlocks_desc': 'Your IVY will unlock in {days} days ({hours} hours).',
    'withdraw.use_instant': 'You can use Instant Cash Out to receive 50% immediately.',
    'withdraw.warning_title': '⚠️ Warning: 50% Penalty',
    'withdraw.warning_desc': 'Instant cash out burns 50% of your locked IVY as a penalty for early withdrawal.',
    'withdraw.you_get': 'You Receive',
    'withdraw.burned': 'Burned',
    'withdraw.cancel': 'Cancel',
    'withdraw.claim_button': 'Claim IVY',
    'withdraw.claiming': 'Claiming...',
    'withdraw.confirm_cashout': 'Confirm Cash Out',
    'withdraw.processing': 'Processing...',

    // ==================== Team Page ====================
    'team.title': 'Team Performance',
    'team.subtitle': 'Track your referral network and earnings',
    'team.referral_link': 'Your Referral Link',
    'team.copy_link': 'Copy Link',
    'team.copied': 'Copied!',
    'team.link_copied': 'Referral link copied!',
    'team.address_copied': 'Address copied!',
    'team.direct_referrals': 'Direct Referrals',
    'team.total_team': 'Total Team Size',
    'team.total_rewards': 'Total Rewards',
    'team.genesis_node': 'Genesis Node',
    'team.active': 'Active',
    'team.inactive': 'Inactive',
    'team.boost': 'Boost',
    'team.up_to_levels': '(up to 20 levels)',
    'team.team_metrics': 'Team Metrics',
    'team.total_bond_power': 'Total Bond Power',
    'team.active_members': 'Active Members',
    'team.avg_bond_power': 'Avg Bond Power',
    'team.active_rate': 'Active',
    'team.direct_list': 'Direct Referrals',
    'team.member': 'Member',
    'team.bond_power': 'Bond Power',
    'team.my_rewards': 'My Rewards',
    'team.status': 'Status',
    'team.no_referrals': 'No direct referrals yet',
    'team.share_link': 'Share your referral link to get started',
    'team.maximize_earnings': 'Maximize Your Earnings',
    'team.reward_l1': 'L1 Direct Referrals',
    'team.reward_l2': 'L2 Indirect Referrals',
    'team.reward_l3': 'L3+ Infinite Team (GenesisNode)',
    'team.reward_peer': 'Peer Level Bonus',
    'team.reward_l1_desc': 'of their rewards',
    'team.reward_l2_desc': 'of their rewards',
    'team.reward_l3_desc': 'from all downlines',
    'team.reward_peer_desc': 'when downline also holds GenesisNode',
  },
  zh: {
    // ==================== 首頁 ====================
    'home.tagline': '系統上線 // V2.5',
    'home.title.line1': '讓時間',
    'home.title.line2': '成為您的盟友',
    'home.subtitle': '首個 PID 控制的結構化債券協議。',
    'home.subtitle.highlight': '算法穩定 // 收益優化',
    'home.cta': '[ 開始鑄造 ]',
    'home.cta.locked': '[ 系統鎖定 ]',
    'home.cta.minting': '[ 鑄造中... ]',
    
    // ==================== 導航 ====================
    'nav.protocol': '首頁',
    'nav.nodes': '節點控制台',
    'nav.yield': '收益終端',
    'nav.team': '團隊業績',
    'nav.docs': '文檔',
    'nav.connect': '連接錢包',
    'nav.faucet': '水龍頭',
    
    // ==================== 通用 ====================
    'common.access_denied': '拒絕訪問',
    'common.return_home': '[ 返回首頁 ]',
    'common.connect_wallet': '請連接您的錢包',
    'common.approve': '[ 授權 USDT ]',
    'common.approving': '[ 授權中... ]',
    'common.approved': '✓ 已授權',
    
    // ==================== 節點頁面 ====================
    'nodes.console': '節點控制台 // 身份層',
    'nodes.title': '創世節點',
    'nodes.description': '購買並管理您的創世節點 NFT。每個節點都能獲得永久算力加成和網絡特權。',
    'nodes.privileges': '節點權益',
    'nodes.self_boost': '自身增幅',
    'nodes.self_boost_desc': '節點持有者永久算力提升',
    'nodes.team_aura': '團隊光環',
    'nodes.team_aura_desc': '賦予所有直推用戶的額外加成',
    'nodes.max_supply': '最大供應量',
    'nodes.max_supply_desc': '限量版創世節點 - 先到先得',
    
    // ==================== 身份面板 ====================
    'identity.title': '身份與權限',
    'identity.subtitle': '創世節點會員資格',
    'identity.current': '當前身份',
    'identity.visitor': '訪客',
    'identity.genesis_node': '創世節點',
    'identity.active': '已激活',
    'identity.privilege_boosts': '權益加成',
    'identity.total_boost': '總算力加成',
    'identity.your_network': '您的網絡',
    'identity.direct_referrals': '直推人數',
    'identity.supply': '供應量',
    'identity.node_price': '節點價格',
    'identity.buy_node': '[ 購買創世節點 ]',
    'identity.buying': '[ 購買中... ]',
    'identity.not_deployed': '合約未部署',
    'identity.deploy_first': '請先部署 GenesisNode 合約',
    
    // ==================== 收益頁面 ====================
    'yield.terminal': '收益終端 // 投資層',
    'yield.title': '國庫債券',
    'yield.description': '存入 USDT 賺取 IVY 代幣。您的投資將自動分配至流動性池、真實資產和儲備池。',
    'yield.genesis_active': '創世節點已激活',
    'yield.boost_message': '您的挖礦收益已獲得加成',
    'yield.no_node': '未持有創世節點',
    'yield.no_node_desc': '購買創世節點可解鎖 +10% 算力加成和 +2% 團隊光環。',
    'yield.go_to_nodes': '前往節點控制台',
    'yield.fund_distribution': '資金分流',
    'yield.liquidity_pool': '流動性池',
    'yield.liquidity_desc': 'DEX 交易對',
    'yield.rwa_wallet': '真實資產錢包',
    'yield.rwa_desc': '真實世界資產',
    'yield.reserve_pool': '儲備池',
    'yield.reserve_desc': '協議保險',
    'yield.referral_rewards': '推廣獎勵',
    'yield.l1_direct': '一級直推',
    'yield.l2_indirect': '二級間推',
    'yield.l3_infinite': '三級及以上',
    'yield.rewards_note': '獎勵來自挖礦池鑄造，不從用戶本金扣除。',
    'yield.how_it_works': '運作方式',
    'yield.step1': '存入',
    'yield.step1_desc': '存入 USDT 創建您的債券',
    'yield.step2': '分流',
    'yield.step2_desc': '資金按 50/40/10 分配',
    'yield.step3': '挖礦',
    'yield.step3_desc': '每日賺取 IVY 代幣',
    'yield.step4': '領取',
    'yield.step4_desc': '每 24 小時領取收益',
    
    // ==================== 資金面板 ====================
    'treasury.title': '資產與增值',
    'treasury.subtitle': '資金投資與挖礦收益',
    'treasury.my_principal': '我的本金',
    'treasury.bond_power': '債券算力',
    'treasury.pool_share': '池子佔比',
    'treasury.est_daily': '預計日產出',
    'treasury.total_claimed': '已領取總額',
    'treasury.referral_earnings': '推廣收益',
    'treasury.fund_distribution': '資金分流 (50/40/10)',
    'treasury.liquidity': '流動性',
    'treasury.rwa': '真實資產',
    'treasury.reserve': '儲備金',
    'treasury.deposit_usdt': '存入 USDT',
    'treasury.balance': '餘額',
    'treasury.deposit_earn': '[ 存入並賺取收益 ]',
    'treasury.depositing': '[ 存入中... ]',
    'treasury.not_deployed': '合約未部署',
    'treasury.deploy_first': '請先部署 IvyBond 合約',
    
    // ==================== 推廣中心 ====================
    'referral.title': '推廣上鏈',
    'referral.description': '直推獎勵 10%，間推獎勵 5%。',
    'referral.your_link': '您的專屬連結',
    'referral.connect_to_generate': '連接錢包以生成連結',
    'referral.copy': '複製',
    'referral.copied': '推廣連結已複製到剪貼板',
    'referral.stats': '推廣統計',
    'referral.direct': '直推人數',
    'referral.direct_refers': '直推人數',
    'referral.ref_rewards': '推廣獎勵',
    'referral.total_earned': '累計收益',
    
    // ==================== 我的節點 ====================
    'myNodes.title': '我的節點',
    'myNodes.wallet_not_connected': '錢包未連接',
    'myNodes.connect_to_view': '連接錢包以查看您的創世節點。',
    'myNodes.no_nodes': '未檢測到節點',
    'myNodes.no_nodes_desc': '初始化創世節點以開始賺取收益。',
    'myNodes.contract': '合約',
    'myNodes.refresh': '刷新',
    'myNodes.genesis_node': '創世節點',
    'myNodes.active': '已激活',
    'myNodes.boost': '加成',
    'myNodes.tier': '等級',
    
    // ==================== 水龍頭 ====================
    'faucet.title': '測試網水龍頭',
    'faucet.subtitle': '僅供開發測試使用',
    'faucet.warning': '此水龍頭僅提供測試代幣供開發使用，這些代幣沒有實際價值。',
    'faucet.your_balance': '您的 MockUSDT 餘額',
    'faucet.amount': '領取數量',
    'faucet.use_for': '用途',
    'faucet.use_for_desc': '購買節點 + 存款',
    'faucet.claim_button': '領取 20,000 mUSDT',
    'faucet.claiming': '領取中...',
    'faucet.success': '代幣領取成功！',
    'faucet.not_deployed': '合約未部署',
    'faucet.deploy_first': '請先部署 MockUSDT 合約',
    
    // ==================== 儀表盤 ====================
    'dashboard.daily_mint': '每日產出',
    'dashboard.nodes': '全網節點',
    'dashboard.your_balance': '您的餘額',
    'dashboard.pid_status': 'PID 狀態',
    'dashboard.genesis': '創世',
    'dashboard.boost_active': '加成激活',
    'dashboard.ivy_per_day': 'IVY / 天',

    // ==================== 資金面板 (新功能) ====================
    'treasury.bond_nft_title': 'Bond NFT 國庫',
    'treasury.bond_nft_subtitle': 'ERC721 挖礦債券 (白皮書 V2.5)',
    'treasury.my_bonds': '我的 Bond NFT',
    'treasury.total_deposit': '總投入',
    'treasury.mining_principal': '礦機本金 (50%)',
    'treasury.rwa_assets': 'RWA 資產 (國債 40%)',
    'treasury.reserve_fund': '儲備金 (10%)',
    'treasury.tranche_b': 'TRANCHE B',
    'treasury.only_this_portion': '僅此部分產生 IVY 挖礦獎勵',
    'treasury.effective_power': '有效挖礦算力',
    'treasury.formula': '公式',
    'treasury.network_share': '網絡算力佔比',
    'treasury.your_power': '您的算力',
    'treasury.total_network': '全網',
    'treasury.ivy_price_title': 'IVY 價格與算力匯率',
    'treasury.testnet': '測試網',
    'treasury.current_price': '當前 IVY 價格',
    'treasury.usdt_per_ivy': 'USDT 每 IVY',
    'treasury.compound_rate': '複投匯率',
    'treasury.power_per_ivy': '每 IVY 算力 (+10% 加成)',
    'treasury.price_formula': '1 IVY = ${price} × 1.1 (複投加成) = {rate} 算力',
    'treasury.pending_vivy': '待收益 (vIVY)',
    'treasury.mining_rewards': '挖礦獎勵 (可複投)',
    'treasury.total_claimed_ivy': '已領取總額',
    'treasury.locked_ivy_title': '鎖定 IVY (30天解鎖)',
    'treasury.unlocks_in': '還需 {days} 天解鎖',
    'treasury.ready_to_claim': '已可領取！',
    'treasury.standard_unlock': '標準解鎖 (100%)',
    'treasury.instant_penalty': '極速提幣 (50% 懲罰)',
    'treasury.compound_title': '複投',
    'treasury.compound_bonus': '+10% 加成',
    'treasury.compound_desc': '白皮書："複投部分的資金給予 10% 的算力加成"',
    'treasury.compound_button': '複投至 Bond NFT',
    'treasury.mining_not_synced': '挖礦算力未同步',
    'treasury.click_to_start': '點擊下方開始賺取獎勵',
    'treasury.sync_now': '立即同步',
    'treasury.syncing': '同步中...',
    'treasury.mint_new_bond': '鑄造新 Bond NFT',
    'treasury.min_deposit': '最低存款：10 USDT',
    'treasury.insufficient_balance': '餘額不足。使用水龍頭。',
    'treasury.mint_button': '鑄造 Bond NFT 並賺取',
    'treasury.minting': '鑄造 Bond NFT 中...',

    // ==================== 收穫區域 ====================
    'harvest.title': '收穫 vIVY',
    'harvest.lock_badge': '鎖定 30 天',
    'harvest.description': '將 vIVY 挖礦獎勵轉換為鎖定的 IVY 代幣。30 天後，選擇標準解鎖（100%）或極速提幣（50% 懲罰）。',
    'harvest.available': '可用 vIVY：',
    'harvest.button': '收穫 {amount} vIVY → 鎖定 IVY',
    'harvest.harvesting': '收穫中...',
    'harvest.success': '收穫成功！{amount} vIVY 已鎖定 30 天 🎉',
    'harvest.no_vivy': '沒有 vIVY 可收穫',
    'harvest.info_toast': '正在收穫 {amount} vIVY → 啟動 30 天鎖定期...',

    // ==================== 複投彈窗 ====================
    'compound.modal_title': '複投 vIVY 至 Bond NFT',
    'compound.select_bond': '選擇 Bond NFT',
    'compound.select_placeholder': '選擇一個債券...',
    'compound.bond_nft': 'Bond NFT',
    'compound.available_vivy': '可用 vIVY (待領獎勵):',
    'compound.amount_label': '複投金額 (vIVY)',
    'compound.enter_amount': '輸入金額...',
    'compound.max': '最大',
    'compound.exceeds_available': '金額超過可用 vIVY',
    'compound.process_title': '複投流程：',
    'compound.step1': '1. vIVY → 轉換為 IVY → 銷毀至 0xdead',
    'compound.step2': '2. 查詢 IVY 價格（測試網：1 IVY = 1 USDT）',
    'compound.step3': '3. 計算算力並獲得 10% 加成',
    'compound.bonus_calc': '加成算力計算：',
    'compound.no_vivy': '沒有可用的 vIVY 複投',
    'compound.need_harvest': '您需要先收穫獎勵',
    'compound.cancel': '取消',
    'compound.confirm': '複投 vIVY',
    'compound.compounding': '複投中...',

    // ==================== 提幣彈窗 ====================
    'withdraw.standard_title': '標準解鎖 (30 天)',
    'withdraw.instant_title': '極速提幣 (50% 懲罰)',
    'withdraw.locked_amount': '鎖定 IVY 數量：',
    'withdraw.unlock_complete': '✅ 解鎖完成！',
    'withdraw.unlock_desc': '您現在可以無損領取全部鎖定金額。',
    'withdraw.you_receive': '您將獲得：',
    'withdraw.still_locked': '⏳ 仍在鎖定中',
    'withdraw.unlocks_desc': '您的 IVY 將在 {days} 天 ({hours} 小時) 後解鎖。',
    'withdraw.use_instant': '您可以使用極速提幣立即獲得 50%。',
    'withdraw.warning_title': '⚠️ 警告：50% 懲罰',
    'withdraw.warning_desc': '極速提幣會銷毀您 50% 的鎖定 IVY 作為提前提取的懲罰。',
    'withdraw.you_get': '您獲得',
    'withdraw.burned': '已銷毀',
    'withdraw.cancel': '取消',
    'withdraw.claim_button': '領取 IVY',
    'withdraw.claiming': '領取中...',
    'withdraw.confirm_cashout': '確認提幣',
    'withdraw.processing': '處理中...',

    // ==================== 團隊頁面 ====================
    'team.title': '團隊業績',
    'team.subtitle': '追蹤您的推薦網絡與收益',
    'team.referral_link': '您的推薦連結',
    'team.copy_link': '複製連結',
    'team.copied': '已複製！',
    'team.link_copied': '推薦連結已複製！',
    'team.address_copied': '地址已複製！',
    'team.direct_referrals': '直推人數',
    'team.total_team': '團隊總人數',
    'team.total_rewards': '累計獎勵',
    'team.genesis_node': '創世節點',
    'team.active': '已激活',
    'team.inactive': '未激活',
    'team.boost': '加成',
    'team.up_to_levels': '(最多 20 層)',
    'team.team_metrics': '團隊指標',
    'team.total_bond_power': '團隊總算力',
    'team.active_members': '活躍成員',
    'team.avg_bond_power': '平均算力',
    'team.active_rate': '活躍',
    'team.direct_list': '直推列表',
    'team.member': '成員',
    'team.bond_power': '債券算力',
    'team.my_rewards': '我的獎勵',
    'team.status': '狀態',
    'team.no_referrals': '暫無直推成員',
    'team.share_link': '分享您的推薦連結開始邀請',
    'team.maximize_earnings': '最大化您的收益',
    'team.reward_l1': '一級直推',
    'team.reward_l2': '二級間推',
    'team.reward_l3': '三級及以上無限代 (創世節點)',
    'team.reward_peer': '平級獎勵',
    'team.reward_l1_desc': '獲得他們的獎勵',
    'team.reward_l2_desc': '獲得他們的獎勵',
    'team.reward_l3_desc': '從所有下級獲得',
    'team.reward_peer_desc': '當下級也持有創世節點時',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
